version: "3"

services:
  challenge-energy-simply-web-container:
    build: ./server
    container_name: challenge-energy-simply-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: challenge-energy-simply:0.11.0
    ports:
      - "80:80"
    depends_on:
      - challenge-energy-simply-db-container
  challenge-energy-simply-db-container:
    image: "microsoft/mssql-server-linux"
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"